spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopping_db?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: lldj123414
    driver-class-name: com.mysql.cj.jdbc.Driver